<?xml version="1.0"?>
<package format="3">
  <name>d3im3r_bot_bringup</name>
  <version>0.1.0</version>
  <description>
    ROS 2 Python package for d3im3r_bot: odometry bridge, safe teleoperation and auxiliary bringup nodes.
  </description>

  <maintainer email="demiranda@unal.edu.co">Deimer Miranda</maintainer>
  <license>MIT</license>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>std_srvs</exec_depend>
  <exec_depend>tf2_ros</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>
  <exec_depend>python3-pynput</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>